### Calculate the distance from location point to closest point from a tornado path/line

In [256]:
import pandas as pd
import math

In [257]:
locDF = pd.read_csv('data/capitals.csv')
torDF = pd.read_csv('data/predicted_data2.csv')

In [258]:
# Add two new empty columns
locDF['minDist'] = 0
locDF['Index'] = 0

locDF

             State    Capital City   Latitude   Longitude  minDist  Index
0          Alabama      Montgomery  32.377716  -86.300568        0      0
1           Alaska          Juneau  58.301598 -134.420212        0      0
2          Arizona         Phoenix  33.448143 -112.096962        0      0
3         Arkansas     Little Rock  34.746613  -92.288986        0      0
4       California      Sacramento  38.576668 -121.493629        0      0
5         Colorado          Denver  39.739227 -104.984856        0      0
6      Connecticut    Hartford<br>  41.764046  -72.682198        0      0
7         Delaware           Dover  39.157307  -75.519722        0      0
8           Hawaii        Honolulu  21.307442 -157.857376        0      0
9          Florida     Tallahassee  30.438118  -84.281296        0      0
10         Georgia     Atlanta<br>  33.749027  -84.388229        0      0
11           Idaho           Boise  43.617775 -116.199722        0      0
12        Illinois     Springfield  39.798363  -89.654961        0      0
13         Indiana    Indianapolis  39.768623  -86.162643        0      0
14            Iowa      Des Moines  41.591087  -93.603729        0      0
15          Kansas          Topeka  39.048191  -95.677956        0      0
16        Kentucky       Frankfort  38.186722  -84.875374        0      0
17       Louisiana     Baton Rouge  30.457069  -91.187393        0      0
18           Maine         Augusta  44.307167  -69.781693        0      0
19        Maryland       Annapolis  38.978764  -76.490936        0      0
20   Massachusetts          Boston  42.358162  -71.063698        0      0
21        Michigan         Lansing  42.733635  -84.555328        0      0
22       Minnesota        St. Paul  44.955097  -93.102211        0      0
23     Mississippi         Jackson  32.303848  -90.182106        0      0
24        Missouri  Jefferson City  38.579201  -92.172935        0      0
25         Montana          Helena  46.585709 -112.018417        0      0
26        Nebraska         Lincoln  40.808075  -96.699654        0      0
27          Nevada     Carson City  39.163914 -119.766121        0      0
28   New Hampshire         Concord  43.206898  -71.537994        0      0
29      New Jersey         Trenton  40.220596  -74.769913        0      0
30      New Mexico        Santa Fe  35.682240 -105.939728        0      0
31  North Carolina         Raleigh  35.780430  -78.639099        0      0
32    North Dakota        Bismarck  46.820850 -100.783318        0      0
33        New York          Albany  42.652843  -73.757874        0      0
34            Ohio        Columbus  39.961346  -82.999069        0      0
35        Oklahoma   Oklahoma City  35.492207  -97.503342        0      0
36          Oregon           Salem  44.938461 -123.030403        0      0
37    Pennsylvania      Harrisburg  40.264378  -76.883598        0      0
38    Rhode Island      Providence  41.830914  -71.414963        0      0
39  South Carolina        Columbia  34.000343  -81.033211        0      0
40    South Dakota          Pierre  44.367031 -100.346405        0      0
41       Tennessee       Nashville  36.165810  -86.784241        0      0
42           Texas          Austin  30.274670  -97.740349        0      0
43            Utah  Salt Lake City  40.777477 -111.888237        0      0
44         Vermont      Montpelier  44.262436  -72.580536        0      0
45        Virginia        Richmond  37.538857  -77.433640        0      0
46      Washington         Olympia  47.035805 -122.905014        0      0
47   West Virginia      Charleston  38.336246  -81.612328        0      0
48       Wisconsin         Madison  43.074684  -89.384445        0      0
49         Wyoming        Cheyenne  41.140259 -104.820236        0      0

In [259]:
torDF

,Unnamed: 0,index,om,yr,tz,stf,stn,mag,inj,fat,...,slon,len,wid,fc,p_elat,p_elon,Time,sDate,sTime,Predicted_Time
0,14,5182,390,1960.0,3,19,10,2,0,0,...,-94.20,1.0,200,0,44.453200,-93.787489,0.0,6/16/1960,13:00:00,1900-01-01 13:00:00
1,29,5130,339,1960.0,3,20,40,0,0,0,...,-97.15,0.1,10,1,0.057051,-0.125474,20.0,6/1/1960,20:00:00,1900-01-02 16:00:00
2,31,4801,9,1960.0,3,1,1,1,0,0,...,-88.10,0.1,10,0,4.640357,-11.252404,16.0,2/4/1960,15:52:00,1900-01-02 07:52:00
3,76,20393,601,1960.0,3,29,33,1,0,0,...,-92.13,0.2,10,0,38.652224,-98.387333,3.0,11/19/1960,13:30:00,1900-01-01 16:30:00
4,105,20207,415,1960.0,3,17,33,2,0,0,...,-88.65,0.1,10,0,45.722189,-96.802818,3.0,6/23/1960,2:00:00,1900-01-01 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371,6577,19993,201,1960.0,3,5,17,2,2,0,...,-93.45,2.6,320,0,17.345008,-30.618189,25.0,5/6/1960,8:30:00,1900-01-02 09:30:00
372,6588,5078,286,1960.0,3,48,29,2,0,0,...,-96.58,2.7,67,0,0.999073,-2.557320,20.0,5/20/1960,5:15:00,1900-01-02 01:15:00
373,6624,20296,504,1960.0,3,38,9,0,0,0,...,-102.90,0.1,10,1,0.126790,-0.375090,92.0,8/2/1960,17:00:00,1900-01-05 13:00:00
374,6642,4929,137,1960.0,3,48,14,1,0,0,...,-96.95,0.2,17,0,35.346239,-95.081721,1.0,5/4/1960,14:40:00,1900-01-01 15:40:00
375,6671,19978,186,1960.0,3,40,58,2,0,0,...,-95.58,1.0,400,0,38.630034,-89.405139,2.0,5/5/1960,21:30:00,1900-01-01 23:30:00

### Find minimum distance (km) from tornado line to location point and then store values in location df

### Formula: https://stackoverflow.com/questions/20231258/minimum-distance-between-a-point-and-a-line-in-latitude-longitude

In [260]:
for i, loc in locDF.iterrows():
    
    for j, tor in torDF.iterrows():

        # Calculate Bearings
        y = math.sin(tor.p_elon - loc.Longitude) * math.cos(tor.p_elat)
        x = math.cos(loc.Latitude) * math.sin(tor.p_elat) - math.sin(loc.Latitude) * math.cos(tor.p_elat) * math.cos(tor.p_elat - loc.Latitude)
        bearing1 = math.degrees(math.atan2(y, x))
        bearing1 = 360 - ((bearing1 + 360) % 360)

        y2 = math.sin(tor.slon - loc.Longitude) * math.cos(tor.slat)
        x2 = math.cos(loc.Latitude) * math.sin(tor.slat) - math.sin(loc.Latitude) * math.cos(tor.slat) * math.cos(tor.slat - loc.Latitude)
        bearing2 = math.degrees(math.atan2(y2, x2))
        bearing2 = 360 - ((bearing2 + 360) % 360)

        # Find location latitude to predicted latitude distance using spherical law of cosines
        lat1Rads = math.radians(loc.Latitude)
        lat3Rads = math.radians(tor.p_elat)
        dLon = math.radians(tor.p_elon - loc.Longitude)

        # Find cross-track distance (6371 == Earth Radius)
        distanceAC = math.acos(math.sin(lat1Rads) * math.sin(lat3Rads)+math.cos(lat1Rads)*math.cos(lat3Rads)*math.cos(dLon)) * 6371
        min_distance = math.fabs(math.asin(math.sin(distanceAC/6371)*math.sin(math.radians(bearing1)-math.radians(bearing2))) * 6371)
        
        #print('min_distance: ', min_distance)
        
        # Set minimum distance variable (km)
        if j == 0:
            locDF.at[i, 'minDist'] = min_distance
            locDF.at[i, 'Index'] = tor['index']# Save index of row with min_dist to loc df
        
        if min_distance < locDF.at[i, 'minDist']:
            locDF.at[i, 'minDist'] = min_distance
            locDF.at[i, 'Index'] = tor['index']# Save index of row with min_dist to loc df

In [261]:
locDF

             State    Capital City   Latitude   Longitude  minDist  Index
0          Alabama      Montgomery  32.377716  -86.300568        3  19821
1           Alaska          Juneau  58.301598 -134.420212       11   4891
2          Arizona         Phoenix  33.448143 -112.096962        6   4914
3         Arkansas     Little Rock  34.746613  -92.288986        2  20399
4       California      Sacramento  38.576668 -121.493629        8   5058
5         Colorado          Denver  39.739227 -104.984856        0  20262
6      Connecticut    Hartford<br>  41.764046  -72.682198        8  20321
7         Delaware           Dover  39.157307  -75.519722        7   4955
8           Hawaii        Honolulu  21.307442 -157.857376       32   5133
9          Florida     Tallahassee  30.438118  -84.281296       11  19980
10         Georgia     Atlanta<br>  33.749027  -84.388229        3   4894
11           Idaho           Boise  43.617775 -116.199722        0   5389
12        Illinois     Springfield  39.798363  -89.654961        3  20123
13         Indiana    Indianapolis  39.768623  -86.162643        0  20060
14            Iowa      Des Moines  41.591087  -93.603729        5  19821
15          Kansas          Topeka  39.048191  -95.677956        1   5031
16        Kentucky       Frankfort  38.186722  -84.875374        0   5031
17       Louisiana     Baton Rouge  30.457069  -91.187393        8  19962
18           Maine         Augusta  44.307167  -69.781693       22  19914
19        Maryland       Annapolis  38.978764  -76.490936        5  19821
20   Massachusetts          Boston  42.358162  -71.063698        9  19980
21        Michigan         Lansing  42.733635  -84.555328        0   4984
22       Minnesota        St. Paul  44.955097  -93.102211        2   5089
23     Mississippi         Jackson  32.303848  -90.182106        3   4810
24        Missouri  Jefferson City  38.579201  -92.172935        8  20214
25         Montana          Helena  46.585709 -112.018417        2   4903
26        Nebraska         Lincoln  40.808075  -96.699654       10   4984
27          Nevada     Carson City  39.163914 -119.766121        7  20355
28   New Hampshire         Concord  43.206898  -71.537994       44   4984
29      New Jersey         Trenton  40.220596  -74.769913        3  20065
30      New Mexico        Santa Fe  35.682240 -105.939728        0  19957
31  North Carolina         Raleigh  35.780430  -78.639099        2   5031
32    North Dakota        Bismarck  46.820850 -100.783318       11   5031
33        New York          Albany  42.652843  -73.757874        1  20370
34            Ohio        Columbus  39.961346  -82.999069        2  20060
35        Oklahoma   Oklahoma City  35.492207  -97.503342        1  20065
36          Oregon           Salem  44.938461 -123.030403        5   5365
37    Pennsylvania      Harrisburg  40.264378  -76.883598        0  20338
38    Rhode Island      Providence  41.830914  -71.414963        8   5048
39  South Carolina        Columbia  34.000343  -81.033211        6  20065
40    South Dakota          Pierre  44.367031 -100.346405        1   4984
41       Tennessee       Nashville  36.165810  -86.784241        0   5333
42           Texas          Austin  30.274670  -97.740349        7  20255
43            Utah  Salt Lake City  40.777477 -111.888237        1  20065
44         Vermont      Montpelier  44.262436  -72.580536       11   5005
45        Virginia        Richmond  37.538857  -77.433640        3  20065
46      Washington         Olympia  47.035805 -122.905014        2  20038
47   West Virginia      Charleston  38.336246  -81.612328        1   5031
48       Wisconsin         Madison  43.074684  -89.384445        7   5256
49         Wyoming        Cheyenne  41.140259 -104.820236       15  20188

In [268]:
def dis(latA, lonA, latB, lonB):
    d = math.acos( math.sin(latA)*math.sin(latB) + math.cos(latA)*math.cos(latB)*math.cos(lonB-lonA) ) * R
    return d

for i, loc in locDF.iterrows():
    
    for j, tor in torDF.iterrows():

        # Calculate Bearings
        y = math.sin(tor.p_elon - loc.Longitude) * math.cos(tor.p_elat)
        x = math.cos(loc.Latitude) * math.sin(tor.p_elat) - math.sin(loc.Latitude) * math.cos(tor.p_elat) * math.cos(tor.p_elat - loc.Latitude)
        bearing1 = math.degrees(math.atan2(y, x))
        bearing1 = 360 - ((bearing1 + 360) % 360)

        y2 = math.sin(tor.slon - loc.Longitude) * math.cos(tor.slat)
        x2 = math.cos(loc.Latitude) * math.sin(tor.slat) - math.sin(loc.Latitude) * math.cos(tor.slat) * math.cos(tor.slat - loc.Latitude)
        bearing2 = math.degrees(math.atan2(y2, x2))
        bearing2 = 360 - ((bearing2 + 360) % 360)

        # Find location latitude to predicted latitude distance using spherical law of cosines
        lat1Rads = math.radians(loc.Latitude)
        lat3Rads = math.radians(tor.p_elat)
        dLon = math.radians(tor.p_elon - loc.Longitude)

        # Find cross-track distance (6371 == Earth Radius)
        distanceAC = math.acos(math.sin(lat1Rads) * math.sin(lat3Rads)+math.cos(lat1Rads)*math.cos(lat3Rads)*math.cos(dLon)) * 6371
        min_distance = math.fabs(math.asin(math.sin(distanceAC/6371)*math.sin(math.radians(bearing1)-math.radians(bearing2))) * 6371)
        
        #print('min_distance: ', min_distance)
        
        # Set minimum distance variable (km)
        if j == 0:
            locDF.at[i, 'minDist'] = min_distance
            locDF.at[i, 'Index'] = tor['index']# Save index of row with min_dist to loc df
        
        if min_distance < locDF.at[i, 'minDist']:
            locDF.at[i, 'minDist'] = min_distance
            locDF.at[i, 'Index'] = tor['index']# Save index of row with min_dist to loc df

In [269]:
locDF

             State    Capital City   Latitude   Longitude  minDist  Index
0          Alabama      Montgomery  32.377716  -86.300568       13  19821
1           Alaska          Juneau  58.301598 -134.420212       11   4891
2          Arizona         Phoenix  33.448143 -112.096962       12   4914
3         Arkansas     Little Rock  34.746613  -92.288986       20  20399
4       California      Sacramento  38.576668 -121.493629        8   5058
5         Colorado          Denver  39.739227 -104.984856        0  20262
6      Connecticut    Hartford<br>  41.764046  -72.682198       24   4795
7         Delaware           Dover  39.157307  -75.519722        9  19993
8           Hawaii        Honolulu  21.307442 -157.857376       40   5133
9          Florida     Tallahassee  30.438118  -84.281296       23   4948
10         Georgia     Atlanta<br>  33.749027  -84.388229       14   5031
11           Idaho           Boise  43.617775 -116.199722        1   5389
12        Illinois     Springfield  39.798363  -89.654961        4   5031
13         Indiana    Indianapolis  39.768623  -86.162643        0  20060
14            Iowa      Des Moines  41.591087  -93.603729        5  19821
15          Kansas          Topeka  39.048191  -95.677956        6   5031
16        Kentucky       Frankfort  38.186722  -84.875374       14   5031
17       Louisiana     Baton Rouge  30.457069  -91.187393        7  19962
18           Maine         Augusta  44.307167  -69.781693       30  20217
19        Maryland       Annapolis  38.978764  -76.490936       24  20385
20   Massachusetts          Boston  42.358162  -71.063698        5  20172
21        Michigan         Lansing  42.733635  -84.555328        0   4984
22       Minnesota        St. Paul  44.955097  -93.102211        2   5089
23     Mississippi         Jackson  32.303848  -90.182106       27   4810
24        Missouri  Jefferson City  38.579201  -92.172935       15  19821
25         Montana          Helena  46.585709 -112.018417        2  19864
26        Nebraska         Lincoln  40.808075  -96.699654       20  20296
27          Nevada     Carson City  39.163914 -119.766121        8  20355
28   New Hampshire         Concord  43.206898  -71.537994       46  20041
29      New Jersey         Trenton  40.220596  -74.769913        6  20065
30      New Mexico        Santa Fe  35.682240 -105.939728        0  19957
31  North Carolina         Raleigh  35.780430  -78.639099        4   5252
32    North Dakota        Bismarck  46.820850 -100.783318       25  20363
33        New York          Albany  42.652843  -73.757874        1  20370
34            Ohio        Columbus  39.961346  -82.999069       12   5031
35        Oklahoma   Oklahoma City  35.492207  -97.503342        3  20065
36          Oregon           Salem  44.938461 -123.030403        6   5365
37    Pennsylvania      Harrisburg  40.264378  -76.883598        0  20338
38    Rhode Island      Providence  41.830914  -71.414963        9   4878
39  South Carolina        Columbia  34.000343  -81.033211       15  20235
40    South Dakota          Pierre  44.367031 -100.346405        5   4984
41       Tennessee       Nashville  36.165810  -86.784241        2   5333
42           Texas          Austin  30.274670  -97.740349        5  20282
43            Utah  Salt Lake City  40.777477 -111.888237       29  20207
44         Vermont      Montpelier  44.262436  -72.580536       19   5005
45        Virginia        Richmond  37.538857  -77.433640        8  20065
46      Washington         Olympia  47.035805 -122.905014        8  20038
47   West Virginia      Charleston  38.336246  -81.612328        3  19821
48       Wisconsin         Madison  43.074684  -89.384445       14  20248
49         Wyoming        Cheyenne  41.140259 -104.820236       66  20321

In [262]:
for i, loc in locDF.iterrows():
    tor = torDF.iloc[1]
    #print(tor)
    # Calculate bearings
    
    y = math.sin(tor.p_elon - loc.Longitude) * math.cos(tor.p_elat)
    x = math.cos(loc.Latitude) * math.sin(tor.p_elat) - math.sin(loc.Latitude) * math.cos(tor.p_elat) * math.cos(tor.p_elat - loc.Latitude)
    bearing1 = math.degrees(math.atan2(y, x))
    bearing1 = 360 - ((bearing1 + 360) % 360)

    y2 = math.sin(tor.slon - loc.Longitude) * math.cos(tor.slat)
    x2 = math.cos(loc.Latitude) * math.sin(tor.slat) - math.sin(loc.Latitude) * math.cos(tor.slat) * math.cos(tor.slat - loc.Latitude)
    bearing2 = math.degrees(math.atan2(y2, x2))
    bearing2 = 360 - ((bearing2 + 360) % 360)

    # Find location latitude to predicted latitude distance using spherical law of cosines
    lat1Rads = math.radians(loc.Latitude)
    lat3Rads = math.radians(tor.p_elat)
    dLon = math.radians(tor.p_elon - loc.Longitude)

    # Find cross-track distance
    distanceAC = math.acos(math.sin(lat1Rads) * math.sin(lat3Rads)+math.cos(lat1Rads)*math.cos(lat3Rads)*math.cos(dLon)) * 6378
    min_distance = math.fabs(math.asin(math.sin(distanceAC/6378)*math.sin(math.radians(bearing1)-math.radians(bearing2))) * 6378)

    # Set minimum distance variable
    if i == 0:
        locDF.at[i, 'minDist'] = min_distance
        #locDF.at[i, 'Index'] = tor['index']# Save index of row with min_dist to loc df
        locDF.at[i, 'Index'] = torDF.at[j, 'index']
    elif min_distance < locDF.at[i, 'minDist']:
        locDF.at[i, 'minDist'] = min_distance
        locDF.at[i, 'Index'] = torDF.at[j, 'index']
        #locDF.at[i, 'Index'] = tor['index']# Save index of row with min_dist to loc df

In [263]:
locDF

             State    Capital City   Latitude   Longitude  minDist  Index
0          Alabama      Montgomery  32.377716  -86.300568     2568  19978
1           Alaska          Juneau  58.301598 -134.420212       11   4891
2          Arizona         Phoenix  33.448143 -112.096962        6   4914
3         Arkansas     Little Rock  34.746613  -92.288986        2  20399
4       California      Sacramento  38.576668 -121.493629        8   5058
5         Colorado          Denver  39.739227 -104.984856        0  20262
6      Connecticut    Hartford<br>  41.764046  -72.682198        8  20321
7         Delaware           Dover  39.157307  -75.519722        7   4955
8           Hawaii        Honolulu  21.307442 -157.857376       32   5133
9          Florida     Tallahassee  30.438118  -84.281296       11  19980
10         Georgia     Atlanta<br>  33.749027  -84.388229        3   4894
11           Idaho           Boise  43.617775 -116.199722        0   5389
12        Illinois     Springfield  39.798363  -89.654961        3  20123
13         Indiana    Indianapolis  39.768623  -86.162643        0  20060
14            Iowa      Des Moines  41.591087  -93.603729        5  19821
15          Kansas          Topeka  39.048191  -95.677956        1   5031
16        Kentucky       Frankfort  38.186722  -84.875374        0   5031
17       Louisiana     Baton Rouge  30.457069  -91.187393        8  19962
18           Maine         Augusta  44.307167  -69.781693       22  19914
19        Maryland       Annapolis  38.978764  -76.490936        5  19821
20   Massachusetts          Boston  42.358162  -71.063698        9  19980
21        Michigan         Lansing  42.733635  -84.555328        0   4984
22       Minnesota        St. Paul  44.955097  -93.102211        2   5089
23     Mississippi         Jackson  32.303848  -90.182106        3   4810
24        Missouri  Jefferson City  38.579201  -92.172935        8  20214
25         Montana          Helena  46.585709 -112.018417        2   4903
26        Nebraska         Lincoln  40.808075  -96.699654       10   4984
27          Nevada     Carson City  39.163914 -119.766121        7  20355
28   New Hampshire         Concord  43.206898  -71.537994       44   4984
29      New Jersey         Trenton  40.220596  -74.769913        3  20065
30      New Mexico        Santa Fe  35.682240 -105.939728        0  19957
31  North Carolina         Raleigh  35.780430  -78.639099        2   5031
32    North Dakota        Bismarck  46.820850 -100.783318       11   5031
33        New York          Albany  42.652843  -73.757874        1  20370
34            Ohio        Columbus  39.961346  -82.999069        2  20060
35        Oklahoma   Oklahoma City  35.492207  -97.503342        1  20065
36          Oregon           Salem  44.938461 -123.030403        5   5365
37    Pennsylvania      Harrisburg  40.264378  -76.883598        0  20338
38    Rhode Island      Providence  41.830914  -71.414963        8   5048
39  South Carolina        Columbia  34.000343  -81.033211        6  20065
40    South Dakota          Pierre  44.367031 -100.346405        1   4984
41       Tennessee       Nashville  36.165810  -86.784241        0   5333
42           Texas          Austin  30.274670  -97.740349        7  20255
43            Utah  Salt Lake City  40.777477 -111.888237        1  20065
44         Vermont      Montpelier  44.262436  -72.580536       11   5005
45        Virginia        Richmond  37.538857  -77.433640        3  20065
46      Washington         Olympia  47.035805 -122.905014        2  20038
47   West Virginia      Charleston  38.336246  -81.612328        1   5031
48       Wisconsin         Madison  43.074684  -89.384445        7   5256
49         Wyoming        Cheyenne  41.140259 -104.820236       15  20188

### Formula: https://stackoverflow.com/questions/32771458/distance-from-lat-lng-point-to-minor-arc-segment

In [264]:
def bear(latA, lonA, latB, lonB):
    b = math.atan2( math.sin(lonB-lonA)*math.cos(latB), math.cos(latA)*math.sin(latB) - math.sin(latA)*math.cos(latB)*math.cos(lonB-lonA) )
    return b

def dis(latA, lonA, latB, lonB):
    d = math.acos( math.sin(latA)*math.sin(latB) + math.cos(latA)*math.cos(latB)*math.cos(lonB-lonA) ) * R
    return d

In [265]:
for i, loc in locDF.iterrows():
    
    for j, tor in torDF.iterrows():

        #tor['slat']=math.radians(tor['slat'])
        #tor[p_elat']=math.radians(tor[p_elat'])
        #loc['Latitude']=math.radians(loc['Latitude'])
        #tor['slon']=math.radians(tor['slon'])
        #tor[p_elon']=math.radians(tor[p_elon']);
        #loc['Longitude']=math.radians(loc['Longitude'])

        R=6371; # Earth's radius in meters
        pi = 3.14159265359
        
        # Prerequisites for the formulas
        bear12 = bear(tor['slat'],tor['slon'],tor['p_elat'],tor['p_elon'])
        bear13 = bear(tor['slat'],tor['slon'],loc['Latitude'],loc['Longitude'])
        #dis12 = dis(tor['slat'],tor['slon'],tor['p_elat'],tor['p_elon'])
        dis12 = dis(torDF.at[j, 'slat'],torDF.at[j, 'slon'],torDF.at[j, 'p_elat'],torDF.at[j, 'p_elon'])
        dis13 = dis(tor['slat'],tor['slon'],loc['Latitude'],loc['Longitude']);
        dis23 = dis(tor['p_elat'],tor['p_elon'],loc['Latitude'],loc['Longitude'])
        disAdd = dis13 + dis23
        disDiff = disAdd - dis12
        
        #dis13 = math.acos( math.sin(tor['slat'])*math.sin(loc['Latitude']) + math.cos(tor['slat'])*math.cos(loc['Latitude'])*math.cos(loc['Longitude']-tor['slon']) ) * R;

        diff = abs(bear13-bear12)

        if diff > pi:
            diff = 2 * pi - diff
            #print(diff)

        # if (distance(A, C) + distance(B, C) == distance(A, B))
        if disDif == dis12: # Is the point on the line?
            dxa = 0            
        elif diff>(pi/2): # Is relative bearing obtuse?
            dxa=dis13
        else:
            #// Find the cross-track distance.
            dxt = math.asin( math.sin(dis13/R)* math.sin(bear13 - bear12) ) * R

            # Is p4 beyond the arc?
            #dis12 = dis(tor['slat'],tor['slon'],tor['p_elat'],tor['p_elon'])
            dis12 = dis(torDF.at[j, 'slat'],torDF.at[j, 'slon'],torDF.at[j, 'p_elat'],torDF.at[j, 'p_elon'])
            #dis12 = math.acos( math.sin(tor['slat'])*math.sin(tor[p_elat']) + math.cos(tor['slat'])*math.cos(tor[p_elat'])*math.cos(tor[p_elon']-tor['slon']) ) * R
            dis14 = math.acos( math.cos(dis13/R) / math.cos(dxt/R) ) * R
            
            if dis14>dis12:
                dxa=dis(tor['p_elat'],tor['p_elon'],loc['Latitude'],loc['Longitude'])
                #dxa = math.acos( math.sin(tor[p_elat'])*math.sin(loc['Latitude']) + math.cos(tor[p_elat'])*math.cos(loc['Latitude'])*math.cos(loc['Longitude']-tor[p_elon']) ) * R
            else:
                dxa=abs(dxt)

        # Set minimum distance variable (km)
        if j == 0:
            locDF.at[i, 'minDist'] = dxa
            locDF.at[i, 'Index'] = tor['index']# Save index of row with min_dist to loc df

        if dxa < locDF.at[i, 'minDist']:
            locDF.at[i, 'minDist'] = dxa
            locDF.at[i, 'Index'] = tor['index']# Save index of row with min_dist to loc df
            
    #print('\n-------------------------')

In [266]:
locDF

             State    Capital City   Latitude   Longitude  minDist  Index
0          Alabama      Montgomery  32.377716  -86.300568        9   5125
1           Alaska          Juneau  58.301598 -134.420212       27  20361
2          Arizona         Phoenix  33.448143 -112.096962      115   4939
3         Arkansas     Little Rock  34.746613  -92.288986      217  20188
4       California      Sacramento  38.576668 -121.493629        0  20327
5         Colorado          Denver  39.739227 -104.984856       83  20060
6      Connecticut    Hartford<br>  41.764046  -72.682198        7  20220
7         Delaware           Dover  39.157307  -75.519722        0   4940
8           Hawaii        Honolulu  21.307442 -157.857376       44   5194
9          Florida     Tallahassee  30.438118  -84.281296        7  19811
10         Georgia     Atlanta<br>  33.749027  -84.388229      179  19948
11           Idaho           Boise  43.617775 -116.199722       49   5137
12        Illinois     Springfield  39.798363  -89.654961        6  19850
13         Indiana    Indianapolis  39.768623  -86.162643        1  20060
14            Iowa      Des Moines  41.591087  -93.603729       80   5288
15          Kansas          Topeka  39.048191  -95.677956        9   5012
16        Kentucky       Frankfort  38.186722  -84.875374       30   5125
17       Louisiana     Baton Rouge  30.457069  -91.187393       16  19842
18           Maine         Augusta  44.307167  -69.781693       25  19863
19        Maryland       Annapolis  38.978764  -76.490936       44   4829
20   Massachusetts          Boston  42.358162  -71.063698        5  19815
21        Michigan         Lansing  42.733635  -84.555328       77  19922
22       Minnesota        St. Paul  44.955097  -93.102211       32   4900
23     Mississippi         Jackson  32.303848  -90.182106       27  20327
24        Missouri  Jefferson City  38.579201  -92.172935       11  20361
25         Montana          Helena  46.585709 -112.018417       83  20297
26        Nebraska         Lincoln  40.808075  -96.699654       11  20296
27          Nevada     Carson City  39.163914 -119.766121       25  19900
28   New Hampshire         Concord  43.206898  -71.537994       18  20279
29      New Jersey         Trenton  40.220596  -74.769913       23   5252
30      New Mexico        Santa Fe  35.682240 -105.939728       54  20364
31  North Carolina         Raleigh  35.780430  -78.639099       50  20300
32    North Dakota        Bismarck  46.820850 -100.783318      335   4800
33        New York          Albany  42.652843  -73.757874      146  20315
34            Ohio        Columbus  39.961346  -82.999069      132   5326
35        Oklahoma   Oklahoma City  35.492207  -97.503342       43  19922
36          Oregon           Salem  44.938461 -123.030403      108  20383
37    Pennsylvania      Harrisburg  40.264378  -76.883598       11   5292
38    Rhode Island      Providence  41.830914  -71.414963      258  20237
39  South Carolina        Columbia  34.000343  -81.033211       78   4810
40    South Dakota          Pierre  44.367031 -100.346405       62  20262
41       Tennessee       Nashville  36.165810  -86.784241       16   4882
42           Texas          Austin  30.274670  -97.740349      290  20038
43            Utah  Salt Lake City  40.777477 -111.888237       93   5020
44         Vermont      Montpelier  44.262436  -72.580536      425  20038
45        Virginia        Richmond  37.538857  -77.433640      295   5020
46      Washington         Olympia  47.035805 -122.905014       23   5011
47   West Virginia      Charleston  38.336246  -81.612328       68   5001
48       Wisconsin         Madison  43.074684  -89.384445      103   4846
49         Wyoming        Cheyenne  41.140259 -104.820236      150  19828